import React, { useEffect, useState } from "react";
import axios from "axios";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Eye, EyeOff, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { useSettings } from "../context/SettingsContext";
import AuthExperience from "./AuthExperience";
import "./Login.css";

const MIN_PASSWORD_LENGTH = 8;
export default function Setup() {
  const navigate = useNavigate(); const { panelName, panelLogo } = useSettings(); const { setupRequired, refreshSetupStatus, markSetupComplete } = useAuth();
  const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [showConfirmPassword, setShowConfirmPassword] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { let active = true; void refreshSetupStatus().then((required: boolean) => { if (!active) return; if (!required) { navigate("/login", { replace: true }); return; } setLoading(false); }); return () => { active = false; }; }, [navigate, refreshSetupStatus]);
  useEffect(() => { if (setupRequired === false && !submitting) navigate("/login", { replace: true }); }, [navigate, setupRequired, submitting]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setSuccess(""); if (!/^[A-Za-z0-9_.-]{3,32}$/.test(username.trim())) { setError("Username must be 3-32 characters using letters, numbers, dots, underscores, or hyphens."); return; } if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim())) { setError("Enter a valid email address."); return; } if (password.length < MIN_PASSWORD_LENGTH || password.length > 256) { setError("Password must be 8-256 characters."); return; } if (password !== confirmPassword) { setError("Passwords do not match."); return; } setSubmitting(true); try { await axios.post("/api/auth/setup", { username: username.trim(), email: email.trim().toLowerCase(), password, confirmPassword }); markSetupComplete(); setSuccess("Owner account created securely. Redirecting..."); window.setTimeout(() => navigate("/login", { replace: true }), 900); } catch (requestError: any) { const responseError = requestError.response?.data; setError(responseError?.error || "Owner setup could not be completed."); if (responseError?.setupRequired === false || requestError.response?.status === 409) markSetupComplete(); } finally { setSubmitting(false); } };
  if (loading) return <main className="auth-loading"><div className="auth-loading__spinner" /><p>Checking secure setup status...</p></main>;
  return <AuthExperience mode="setup" panelName={panelName} panelLogo={panelLogo} eyebrow="Secure first-run setup" title="Create the owner account" description="This protected setup is available only while no user exists." footer={<>Already completed setup? <Link to="/login">Sign in</Link></>}>
    {error && <div className="auth-alert" role="alert">{error}</div>}{success && <div className="auth-success" role="status">{success}</div>}
    <form onSubmit={submit} className="auth-form" noValidate aria-busy={submitting}>
      <label className="auth-field"><span>Owner username</span><div className="auth-input"><UserRound size={17} /><input autoComplete="username" required value={username} onChange={(event) => setUsername(event.target.value)} placeholder="owner" /></div></label>
      <label className="auth-field"><span>Owner email</span><div className="auth-input"><Mail size={17} /><input type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="owner@example.com" /></div></label>
      <div className="auth-form-grid"><label className="auth-field"><span>Password</span><div className="auth-input"><LockKeyhole size={17} /><input type={showPassword ? "text" : "password"} autoComplete="new-password" required minLength={MIN_PASSWORD_LENGTH} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 8 characters" /><button type="button" className="auth-password-toggle" onClick={() => setShowPassword((visible) => !visible)} aria-label="Toggle password visibility">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label><label className="auth-field"><span>Confirm password</span><div className="auth-input"><LockKeyhole size={17} /><input type={showConfirmPassword ? "text" : "password"} autoComplete="new-password" required minLength={MIN_PASSWORD_LENGTH} value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Repeat password" /><button type="button" className="auth-password-toggle" onClick={() => setShowConfirmPassword((visible) => !visible)} aria-label="Toggle confirmation visibility">{showConfirmPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></label></div>
      <p className="auth-helper">The first account receives Owner access. Snck never creates a default password.</p><button type="submit" className="auth-submit" disabled={submitting || Boolean(success)}><span>{submitting ? "Creating Owner account..." : "Create Owner account"}</span>{!submitting && <ArrowRight size={17} />}</button>
    </form>
  </AuthExperience>;
}
