import express from "express";
import {requireAdmin} from "../middleware/auth.js";
import {connectCloudflare,getAccount,listZones,listDns,createDns,updateDns,deleteDns,getZone} from "../services/cloudflare.js";
import {audit,rateLimit} from "../services/security.js";
const r=express.Router();r.use(requireAdmin,rateLimit());
r.get("/connection",async(req,res)=>{try{const a=await getAccount();res.json({connected:true,id:a.id,accountId:a.accountId,createdAt:a.createdAt})}catch{res.json({connected:false})}});
r.post("/connection",async(req,res)=>{try{const {token,accountId}=req.body;if(!token)return res.status(400).json({error:"Token required"});const result=await connectCloudflare(token,accountId);await audit("cloudflare.connected",req,{accountId:result.accountId});res.status(201).json({id:result.id,accountId:result.accountId})}catch(e:any){res.status(400).json({error:e.message})}});
r.get("/zones",async(req,res)=>{try{res.json(await listZones(String(req.query.accountId||"")))}catch(e:any){res.status(502).json({error:e.message})}});
r.get("/zones/:zoneId",async(req,res)=>{try{res.json(await getZone(req.params.zoneId))}catch(e:any){res.status(502).json({error:e.message})}});
r.get("/zones/:zoneId/dns",async(req,res)=>{try{res.json(await listDns(req.params.zoneId))}catch(e:any){res.status(502).json({error:e.message})}});
r.post("/zones/:zoneId/dns",async(req,res)=>{try{const x=await createDns(req.params.zoneId,req.body);await audit("cloudflare.dns.created",req,{zoneId:req.params.zoneId,recordId:x.id,type:x.type,name:x.name});res.status(201).json(x)}catch(e:any){res.status(502).json({error:e.message})}});
r.put("/zones/:zoneId/dns/:recordId",async(req,res)=>{try{const x=await updateDns(req.params.zoneId,req.params.recordId,req.body);await audit("cloudflare.dns.updated",req,{zoneId:req.params.zoneId,recordId:req.params.recordId});res.json(x)}catch(e:any){res.status(502).json({error:e.message})}});
r.delete("/zones/:zoneId/dns/:recordId",async(req,res)=>{try{const x=await deleteDns(req.params.zoneId,req.params.recordId);await audit("cloudflare.dns.deleted",req,{zoneId:req.params.zoneId,recordId:req.params.recordId});res.json(x)}catch(e:any){res.status(502).json({error:e.message})}});
export default r;
